SellIt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import *
from django.contrib import admin
import os.path
from django.views.generic import TemplateView
site_media = os.path.join(
os.path.dirname(__file__), 'templates/static'
)

admin.autodiscover()
from app.views import  *
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SellIt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^$', home),
    url(r'^search/$', search),
    url(r'^cat/(?P<cat_id>\d+)/$', category_page),
    url(r'^register/success/$',  TemplateView.as_view(template_name ='registration/success.html')),
    url(r'^logout/$', logout_page),    
    url(r'^order/(?P<item_id>\d+)/$', order),
    url(r'^item_feedback/$', item_feedback),        
    url(r'^order/submit/$', order_submit),        
    url(r'^track_order/$', track_order),
    (r'^register/$', register_page),

    url(r'^login/$', 'django.contrib.auth.views.login'),    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^detail/(?P<item_id>\d+)/$', detail),
    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
{ 'document_root': site_media }),

)

app/forms.py
from django import  forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class RegistrationForm(forms.Form):
	username = forms.CharField(label='Username', max_length=30)
	email = forms.EmailField(label='Email')
	#address=forms.CharField(
	#	label='Address',
	#	);
	password1 = forms.CharField(
		label='Password',
		widget=forms.PasswordInput()
		)
	password2 = forms.CharField(
		label='Password (Again)',
		widget=forms.PasswordInput()
		)
	def clean_password2(self):
		if 'password1' in self.cleaned_data:
			password1 = self.cleaned_data['password1']
			password2 = self.cleaned_data['password2']
			if password1 == password2:
				return password2
		raise forms.ValidationError('Passwords do not match.')
	def clean_username(self):
		username = self.cleaned_data['username']
		if not re.search(r'^\w+$', username):
			raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
		try:
			User.objects.get(username=username)
		except ObjectDoesNotExist:
			return username
		raise forms.ValidationError('Username is already taken.')

class orderForm(forms.Form):
	address=forms.CharField()
	

SellIt/templates/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>SellIt | Home</title>

    <!-- Bootstrap core CSS -->
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/site_media/css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="/site_media/css/star-rating.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/site_media/css/navbar-fixed-top.css" rel="stylesheet">
    <script src="/site_media/js/jquery.js"></script>
    <script src="/site_media/js/bootstrap.min.js"></script>
    <script src="/site_media/js/docs.min.js"></script>
    <script src="/site_media/js/star-rating.js"></script>
    <script src="/site_media/js/docs.min.js"></script>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style type="text/css">
textarea{
        resize:none;
    }

  </style>
  </head>


  <body role="document">

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">SellIt 
            {% if user.username %}
            | Hello <b>{{user.username|title}}</b>
            {% endif %}
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li ><a href="/">Home</a></li>
            <li><a href="/track_order">Track Order</a></li>
            {% if user.username %}
            <li><a href="/logout/">Logout</a></li>
            {% else %}
            <li><a href="/login/">Login</a></li>
            {% endif %}

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<div class="col-md-3">
{% if related_item|length > 1 %}
  
    <h4> Related Items</h4>
  <div class="row"> 
  {% for item in related_item %}
    {% if item_detail.id == item.item.id %}
      {% else %} 
          <div class="col-xs-4 col-md-4">
              <a href='/detail/{{item.item.id}}' class="thumbnail"><img src='{{item.thumbnail}}' style="min-height:50px;height:50px;"></a>
          </div>
    {% endif %}  
  {% endfor %}
  </div>
{% endif %}   

{% if itembought|length > 1 %}
  <h4>People who bought this</h4>
  <div class="row"> 
  {% for user in itembought %}
    <div class="col-xs-12 col-md-12">
      <a href='#' class="thumbnail">{{user.order.order_by|title}}<hr>
      {{user.order.shipping_address}}</a>
    </div>  
  {% endfor %}
  </div>
{% endif %}
</div>
<div class="col-md-8"> 
{% if item_detail %}
  <div class="panel panel-default">
  <div class="panel-body">
   <h2>{{item_detail.name}}</h2>
  </div>
  <div class="panel-footer">
  </div>
  </div>  
     <div class="col-md-6"> 
      <img src='{{item_pictures.url}}'>
     </div>
     <div class="col-md-6"> 

                  <input type="number " id="star_feedback_avg" showCaption="false" class="rating" size="xs" value="{{avg_rating}}" disabled="true" >
                  <script type="text/javascript">
                    $("#star_feedback_avg").rating();
                  </script>     
                  <h3>Price : INR {{item_detail.selling_price}}</h3>
                  <h3>Stock Left : {{item_detail.stock_left}}</h3>
                  <h3>Provider : {{item_detail.added_by}}</h3>
                <a roll="button" class="btn btn-primary" href="/order/{{item_detail.id}}">Buy this</a>
     </div>      
  
  
  </div>  
  <div class="col-md-12"> 
    <div class="col-md-3"> 
    </div>  
    
    <div class="col-md-8"> 
            <h2>Comments and Feedback</h2>

          {% if user.username %}


            <hr>
           {% if userFeedbackYN.given == True %}
            {% for feed in userFeedbackYN.feedback %}

            <h2>Your Feedback</h2>
              
              <input type="number " id="star_feedback0" showCaption="false" class="rating" size="xs" value="{{feed.stars_given}}" disabled="true" >
              <textarea class="form-control" rows="3"  disabled> {{feed.comment}} </textarea> 
              <br>
              
            {% endfor %} 



           {% else %} 
            <h2>Add your feedback</h2>  
            <form class="form-horizontal" role="form" method="post" id="feedback_form" >
            {% csrf_token %}
            <input type="number " id="star_feedback0" showCaption="false" class="rating" size="xs"  name="star" >
            <textarea class="form-control" rows="3" name="feedback"> </textarea> 
            <input type="hidden" name="item_id" value="{{item_detail.id}}"/>
            <input type="submit" class="btn btn-default" roll="button" />  
           {% endif %} 
          <script type="text/javascript">
                $("#star_feedback0").rating();
          </script>     
          {% endif %}

          {% for feed in feedback %}
           <hr>     
          <h2>{{feed.user}}</h2>
           
              <input type="number " id="star_feedback{{forloop.counter}}" showCaption="false" class="rating" size="xs" value="{{feed.stars_given}}" disabled="true" >

              <textarea class="form-control" rows="3"  disabled> {{feed.comment}} </textarea> 

          <script type="text/javascript">
                $("#star_feedback{{forloop.counter}}").rating();
            </script>   
          {% endfor %}
          </div>
          {% else %}
              <p>No Items are available.</p>
          {% endif %}

    </div>        
</div>
    </div> <!-- /container -->
<script type="text/javascript">
    
      $( "#feedback_form" ).submit(function( event ) {
            
            event.preventDefault();
            data=$("#feedback_form").serialize();
            $.ajax({
              url:'/item_feedback/',
              method:'POST',
              data:data,
              dataType:"html",
              success:function(data) {
                alert("Feedback Added Successfully");
                window.location.reload();
              }

            });
});

  </script>   

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    

  </body>
</html>

SellIt/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>SellIt | Home</title>

    <!-- Bootstrap core CSS -->
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/site_media/css/bootstrap-theme.min.css" rel="stylesheet">
    <script src="/site_media/css/jquery-ui.css"></script>
    <!-- Custom styles for this template -->
    <link href="/site_media/css/navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style>
  #sidebar {
  margin-left: 0px;
  top: 10px;
  bottom: 0px;
  min-height: 100%;
}

 
#sidebar > .nav > .nav-menu > a {
  border: 0px;
  border-radius: 0px;
  padding: 20px;
}
#menuactive{
  background-color: #2C2C2C;
} 
#main {
  float: right;
}
  </style>
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">SellIt 
            {% if user.username %}
            | Hello <b>{{user.username|title}}</b>
            {% endif %}
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/track_order">Track Order</a></li>
            {% if user.username %}
            <li><a href="/logout/">Logout</a></li>
            {% else %}
            <li><a href="/login/">Login</a></li>
            <li><a href="/register/">Register</a></li>
            {% endif %}
            
          </ul>
        </div><!--/.nav-collapse --> 
            
          
        
      </div>
    </div>

<div class="col-md-3">
  <div class="right-inner-addon">
        <i class="icon-search"></i>
        
        <input list="mainsearch" id="input" name="search" class="form-control" placeholder="Search">
          <datalist id="mainsearch">
          </datalist>
  </div> 
<hr>

<div id="sidebar" class="sidebar-nav span3">
            <ul class="nav nav-tabs nav-stacked">
              {% if cat_id|add:0 == 0 %}              
                <li class="nav-menu" id='menuactive' ><a href="/">Home</a></li>
              {% else %}
                <li class="nav-menu"  ><a href="/">Home</a></li>
              {% endif %}
                    
              {% if category %}

                {% for cat in category %}

                  {% if cat.id == cat_id|add:0 %}
                    <li class="nav-menu " id='menuactive' ><a href="/cat/{{cat.id}}">{{ cat.type_name}}</a></li>
                
                  {% else %}
                    <li class="nav-menu "  ><a href="/cat/{{cat.id}}">{{ cat.type_name}}</a></li>
                  {% endif %}    
                {% endfor %}  
              {% endif %}    
            </ul>
</div>
{% if recently_viewd %}
  <div class="col-md-12">
    <h4> Last Viewed by you</h4>
  <div class="row"> 
  {% for item in recently_viewd %}
    <div class="col-xs-4 col-md-4">      
      <a href='/detail/{{item.id}}' class="thumbnail"><img src='{{item.thumbnail}}' style="min-height:50px;height:50px;"></a>
    </div>
  {% endfor %} 
</div>
</div>
{% endif %}    
</div>
{% if all_items %}
  <div class="col-md-8" >
  <div class="row"> 
  {% for item in all_items %}  
    <div class="col-sm-6 col-md-3" >
      <div class="thumbnail">
        <img  src='{{item.thumbnail}}' alt="{{item.name}}" style="min-height:100px;height:100px;">
        <div class="caption" style="text-align: center">
          <h5>{{item.item.name|slice:":20"}}</h5>
          <h5>Price : INR {{item.item.selling_price}}</h5>
          <p> <a href="/detail/{{item.item_id}}" class="btn btn-default" role="button">Details</a></p>
        </div>
      </div>
    </div>
  {% endfor %} 
  </div>
  </div>
{% else %}
    <p>No Items are available.</p>
{% endif %}
  
  


  


  </div>
<div id="output">

</div>



    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/site_media/js/core.js"></script>
    <script src="/site_media/js/jquery.js"></script>
    
<script type="text/javascript">
  var mapp=[];
      $( document ).ready(function() {
                $.ajax({
                      type: "GET",
                      dataType: "json",
                      url:"/search/",
                      success: function(item)
                      {
                        var obj = eval(item.item);
                        for(var i=0;i<obj.length;i++){
                          mapp[obj[i].fields.name]=obj[i].pk;
                          var opt="<option value='"+obj[i].fields.name+"'>";
                          $('#mainsearch').append(opt);
                          }
                      },
                });
        
      });


    var datalist = document.getElementById ("mainsearch");
    var input = document.getElementById ("input");

    input.addEventListener ("keyup", function (event) {
        if (event.which === 13) {
             window.location="/detail/"+mapp[input.value];
        }
    }, false);

  </script>

    <script src="/site_media/js/jquery-ui.js"></script>
    <script src="/site_media/js/bootstrap.min.js"></script>
    <script src="/site_media/js/docs.min.js"></script>
  </body>
</html>

SellIt/templates/order.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>SellIt | Order</title>

    <!-- Bootstrap core CSS -->
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/site_media/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/site_media/css/navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">SellIt </a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li ><a href="/">Home</a></li>
            <li><a href="/track_order">Track Order</a></li>
            {% if user.username %}
            <li><a href="/logout/">Logout</a></li>
            {% else %}
            <li ><a href="/login/">Login</a></li>
            <li class="active"><a href="/register/">Register</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container theme-showcase" role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Fill Details to buy {{item_detail.name}}</h3>
            </div>
            <div class="panel-body">
            
            <div class="col-sm-6"> 

             <form class="form-horizontal" role="form" method="post" action="/order/submit/">
              {% csrf_token %}
              <input type="hidden" name="next" value="/" />
              <div class="form-group">
                <label for="id_address" class="col-sm-2 control-label">Address</label>
                <div class="col-sm-8">
              <textarea class="form-control" rows="3" name="id_address" placeholder="Shipping Address"></textarea>
                </div>
              </div>

              <div class="form-group">
                <label for="id_price" class="col-sm-2 control-label">Delivery Charges</label>
                <div class="col-sm-8">
                  <input class="form-control" id="disabledInput"  type="text" placeholder="INR 0.0"  disabled >
                </div>
              </div>

              <div class="form-group">
                <label for="id_price" class="col-sm-2 control-label">Total Price</label>
                <div class="col-sm-8">
                  <input class="form-control" id="disabledInput"  type="text" placeholder="INR {{item_detail.selling_price}}" disabled >
                  <input type="hidden" name="id_totalprice" value="{{item_detail.selling_price}}">
                  <input type="hidden" name="id_itemid" value="{{item_detail.id}}">
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-8">
                  <button type="submit" class="btn btn-default" >Submit</button>
                </div>
              </div>

            </form>
            </div>

            <div class="col-sm-4">  
            </div>  
            </div>
          </div>
      </div>



    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/site_media/js/jquery.js"></script>
    <script src="/site_media/js/core.js"></script>    
    <script src="/site_media/js/bootstrap.min.js"></script>
    <script src="/site_media/js/docs.min.js"></script>
  </body>
</html>

SellIt/templates/order_success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>SellIt | Success</title>

    <!-- Bootstrap core CSS -->
    <link href="/site_media/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/site_media/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/site_media/css/navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">SellIt </a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li ><a href="/">Home</a></li>
            <li><a href="/track_order">Track Order</a></li>
            {% if user.username %}
            <li><a href="/logout/">Logout</a></li>
            {% else %}
            <li ><a href="/login/">Login</a></li>
            <li class="active"><a href="/register/">Register</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container theme-showcase" role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Thank you</h3>
            </div>
            <div class="panel-body">
            
            <div class="col-sm-8">
             <h2>Successfully Ordered !! Your Order Id is {{orderid}}</h2>  <a href='/'>Click Here</a>
            </div>  
            </div>
          </div>
      </div>



    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/site_media/js/jquery.js"></script>
    <script src="/site_media/js/bootstrap.min.js"></script>
    <script src="/site_media/js/docs.min.js"></script>
  </body>
</html>